INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (1, 'Subotica', '24000', 1);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (2, 'Backa Topola', '24300', 1);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (3, 'Zrenjanin', '23000', 2);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (4, 'Novi Becej', '23272', 2);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (5, 'Kanjiza', '24420', 3);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (6, 'Senta', '24400', 3);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (7, 'Pancevo', '26000', 4);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (8, 'Vrsac', '26300', 4);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (9, 'Sombor', '25000', 5);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (10, 'Apatin', '25260', 5);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (11, 'Novi Sad', '21000', 6);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (12, 'Beocin', '21220', 6);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (13, 'Ruma', '22400', 7);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (14, 'Sremska Mitrovica', '22000', 7);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (15, 'Sabac', '15000', 8);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (16, 'Loznica', '15300', 8);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (17, 'Valjevo', '14000', 9);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (18, 'Ljig', '14244', 9);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (19, 'Smederevo', '11300', 10);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (20, 'Velika Plana', '11320', 10);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (21, 'Pozarevac', '12000', 11);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (22, 'Veliko Gradiste', '12220', 11);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (23, 'Kragujevac', '34000', 12);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (24, 'Arandjelovac', '34300', 12);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (25, 'Jagodina', '35000', 13);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (26, 'Cuprija', '35230', 13);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (27, 'Bor', '19210', 14);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (28, 'Negotin', '19300', 14);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (29, 'Zajecar', '19000', 15);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (30, 'Sokobanja', '18230', 15);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (31, 'Uzice', '31000', 16);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (32, 'Sjenica', '36310', 16);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (33, 'Gornji Milanovac', '32300', 17);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (34, 'Cacak', '32000', 17);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (35, 'Kraljevo', '36000', 18);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (36, 'Raska', '36350', 18);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (37, 'Krusevac', '37000', 19);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (38, 'Trstenik', '37240', 19);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (39, 'Nis', '18000', 20);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (40, 'Razanj', '18220', 20);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (41, 'Prokuplje', '18400', 21);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (42, 'Blace', '18254', 21);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (43, 'Pirot', '18300', 22);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (44, 'Dimitrovgrad', '18320', 22);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (45, 'Leskovac', '16000', 23);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (46, 'Medvedja', '16240', 23);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (47, 'Vranje', '17000', 24);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (48, 'Bosilegrad', '17540', 24);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (49, 'Pristina', '38200', 25);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (50, 'Obilic', '38240', 25);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (51, 'Pec', '30000', 26);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (52, 'Istok', '30250', 26);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (53, 'Prizren', '20000', 27);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (54, 'Orahovac', '20070', 27);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (55, 'Kosovska Mitrovica', '38220', 28);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (56, 'Vucitrn', '38233', 28);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (57, 'Gnjilane', '38230', 29);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (58, 'Kosovska Kamenica', '38260', 29);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (59, 'Vrbas', '21460', 1);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (60, 'Sid', '22240', 3);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (61, 'Beograd', '11000', 8);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (62, 'Osijek', '31000', 11);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (63, 'Dubrovnik', '20000', 12);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (64, 'Sarajevo', '71000', 10);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (65, 'Tuzla', '75000', 10);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (66, 'Vukovar', '32000', 11);
INSERT INTO MLJ_CITY (cityId, cityName, postalCode, MLJ_REGION_regionId) VALUES (67, 'Kikinda', '23300', 2);