insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (57, 2, '04-Oct-1963', 'Filia', 'Moores', '6211 Ruskin Way');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (28, 3, '09-Oct-1961', 'Eli', 'Cooney', '932 Buena Vista Way');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (67, 4, '30-Jun-1980', 'Syd', 'Copestake', '763 Welch Place');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (6, 5, '15-May-1974', 'Aldrich', 'Angless', '7 Quincy Way');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (25, 6, '30-Jul-1994', 'Andrew', 'McCleary', '479 Stuart Point');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (13, 7, '04-Jul-1970', 'Dyanna', 'Clayfield', '80 Toban Junction');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (27, 8, '19-Jan-1966', 'Bev', 'Lafee', '16083 Crownhardt Hill');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (58, 9, '08-May-1990', 'Pattin', 'Blindermann', '974 Fuller Center');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (31, 10, '04-Oct-1992', 'Chelsae', 'Currum', '83181 High Crossing Avenue');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (49, 11, '29-Dec-1997', 'Halie', 'Mapledoram', '018 Havey Center');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (32, 12, '26-Oct-1987', 'Nicolis', 'Mattisson', '1652 Hollow Ridge Way');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (67, 13, '09-Jan-1962', 'Harriette', 'Bayston', '559 Randy Junction');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (56, 14, '25-Jun-1973', 'Dorelia', 'Swinford', '137 Macpherson Avenue');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (55, 15, '02-Nov-1998', 'Fredia', 'Haydney', '96 Harper Way');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (37, 16, '09-Jun-1977', 'Bellanca', 'Fairebrother', '9 Pearson Trail');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (48, 17, '07-Aug-1994', 'Johan', 'Cotillard', '870 Forest Dale Way');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (3, 18, '28-May-1967', 'Terri-jo', 'Grovier', '8 customerNamekagon Crossing');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (5, 19, '17-Jul-1966', 'Burg', 'Gutch', '4 Buell Crossing');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (27, 20, '07-Jan-1963', 'Jill', 'Gresley', '33555 Atwood Drive');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (18, 1, '18-Sep-1998', 'Ashleigh', 'Charlesworth', '717 Main Road');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (10, 21, '23-Apr-1960', 'Morlee', 'Tames', '8988 Park Meadow Street');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (37, 22, '10-Aug-1998', 'Alexia', 'Jales', '338 Granby Road');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (58, 23, '11-Sep-1976', 'Jenny', 'Leblanc', '5 Lawn Hill');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (13, 24, '06-Jul-1998', 'Marje', 'Dunbar', '46519 Tomscot Road');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (60, 25, '09-Sep-1992', 'Pauline', 'Salzen', '29840 Briar Crest Point');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (43, 26, '05-Sep-1981', 'Corella', 'Paschek', '7 Blaine Court');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (13, 27, '20-Jun-1987', 'Zachary', 'Rens', '05 Doe Crossing Place');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (37, 28, '13-Oct-1976', 'Julienne', 'Erasmus', '3107 Sunnyside Crossing');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (55, 29, '15-Jan-1986', 'Rosemaria', 'Toomer', '85 Clove Center');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (32, 30, '13-Dec-1962', 'Vasili', 'Swateridge', '8470 Pankratz Alley');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (66, 31, '23-Dec-1971', 'Dido', 'Winks', '74 Boyd Terrace');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (46, 32, '04-Mar-1989', 'Dotti', 'O''Duane', '2098 Killdeer Point');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (35, 33, '01-Apr-1983', 'Desdemona', 'Soppit', '2172 Ilene Parkway');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (56, 34, '12-Mar-1987', 'Lenee', 'McClelland', '95375 Maple Hill');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (6, 35, '15-Mar-1982', 'Dorena', 'Sanney', '9 Mesta Alley');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (16, 36, '18-Oct-1995', 'Dionysus', 'Wilprecht', '7 Karstens Parkway');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (13, 37, '03-Jan-1976', 'Rob', 'Edeler', '151 Blue Bill Park Lane');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (52, 38, '14-Aug-1997', 'Sibby', 'Mackett', '86 Sauthoff Court');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (2, 39, '15-Nov-1966', 'Talbot', 'Aronovitz', '818 8th Hill');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (5, 40, '28-Apr-1980', 'Gaylene', 'Dowda', '4 New Castle Parkway');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (23, 41, '08-Dec-1980', 'Dillie', 'Lainge', '6830 Lawn Court');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (44, 42, '05-May-1994', 'Blisse', 'Haselden', '434 5th Park');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (44, 43, '11-Mar-1988', 'Lawrence', 'Erskin', '02097 Lyons Lane');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (8, 44, '02-Oct-1980', 'Case', 'Gorcke', '9 Maywood Junction');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (26, 45, '09-Oct-1989', 'Florenza', 'Godbold', '0 Maple Pass');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (58, 46, '10-Jul-1981', 'Claus', 'Yantsurev', '7809 Everett Pass');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (49, 47, '06-Oct-1999', 'Esdras', 'Druery', '87 Debra Hill');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (26, 48, '13-Nov-1992', 'Chev', 'Srawley', '90968 Schurz Drive');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (2, 49, '29-Nov-1971', 'Moina', 'Beston', '3 Vera Point');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (38, 50, '19-Jul-1974', 'Kyle', 'Sellman', '48338 Straubel Road');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (53, 51, '19-Jun-1984', 'Yurik', 'Creeghan', '5 Bobwhite Crossing');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (16, 52, '11-Oct-1972', 'Tally', 'Gietz', '5 Maywood Center');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (63, 53, '27-Jul-1976', 'Page', 'Vacher', '67 Washington Avenue');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (5, 54, '31-Jul-1988', 'Phillis', 'Alcalde', '1 Prairieview Way');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (53, 55, '16-May-1964', 'Josefina', 'Argabrite', '569 Forster Road');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (56, 56, '29-Apr-1977', 'Gothart', 'Denyer', '27245 Crescent Oaks Road');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (11, 57, '10-May-1984', 'Jamie', 'Behneke', '624 Lawn Pass');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (52, 58, '05-Jan-1990', 'Marcelia', 'Avrahamy', '081 Lakeland Park');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (1, 59, '05-Feb-1987', 'Tedman', 'Drinkel', '5 Sundown Road');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (11, 60, '10-Apr-1993', 'Maurie', 'Enstone', '65795 Sachtjen Parkway');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (10, 61, '04-Oct-1979', 'Sherill', 'Swynfen', '57273 Melody Pass');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (67, 62, '18-Oct-1969', 'Virginie', 'Saggers', '6733 Toban Road');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (19, 63, '05-Mar-1967', 'Judith', 'Tidbald', '1445 Hermina Alley');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (14, 64, '11-Mar-1983', 'Grace', 'Creaney', '15571 Marcy Junction');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (40, 65, '21-May-1960', 'Serene', 'Lyver', '00 Anniversary Parkway');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (18, 66, '17-Sep-1960', 'Archaimbaud', 'Rennels', '6557 Luster Junction');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (28, 67, '09-Aug-1999', 'Zahara', 'Karpol', '14698 Fieldstone Junction');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (65, 68, '22-Apr-1996', 'Farley', 'Tremolieres', '55127 Swallow Circle');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (10, 69, '13-Jul-1961', 'Silvio', 'Baker', '648 Dennis Terrace');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (21, 70, '04-Oct-1983', 'Andi', 'Cinelli', '03681 Harbort Hill');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (36, 71, '16-Dec-1988', 'Wyn', 'Graddon', '6229 Saint Paul Park');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (35, 72, '20-Aug-1990', 'Aleda', 'Foyster', '0292 Oak Valley Park');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (45, 73, '18-May-1960', 'Marlow', 'Goddert.sf', '4361 Center Trail');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (59, 74, '28-Oct-1978', 'Tami', 'Draper', '6530 Brickson Park Plaza');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (21, 75, '17-Mar-1970', 'Arnie', 'McAleese', '60 Westend Lane');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (2, 76, '10-Dec-1982', 'Raleigh', 'Wicklin', '4 Susan Drive');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (33, 77, '12-Mar-1971', 'Wally', 'Kindle', '6259 Green Ridge Center');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (12, 78, '10-Nov-1981', 'Dwain', 'Drewe', '08543 Hoffman Street');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (6, 79, '02-Dec-1978', 'Clerkclaude', 'Abbet', '65905 Luster Junction');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (21, 80, '31-May-1970', 'Dud', 'Flieger', '6 Cody Crossing');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (65, 81, '23-Feb-1978', 'Jon', 'Barbey', '7 Ramsey Plaza');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (59, 82, '08-Jun-1971', 'Diann', 'Fairbairn', '4388 Sunfield Crossing');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (26, 83, '30-Aug-1978', 'Valdemar', 'de Nore', '5 Schiller Trail');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (5, 84, '17-Dec-1978', 'Rozina', 'Ireland', '9 Meadow Vale Drive');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (27, 85, '27-Aug-1981', 'Itch', 'Kadar', '12089 Golf View Alley');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (29, 86, '29-Jan-1997', 'Ania', 'Walewski', '75856 Ridgeway Circle');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (7, 87, '04-Sep-1979', 'Gerik', 'Ilewicz', '0 Northwestern Parkway');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (26, 88, '26-Jul-1964', 'Billye', 'Floyd', '7 Gulseth Crossing');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (3, 89, '13-May-1976', 'Calhoun', 'Armour', '2649 Mayer Place');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (15, 90, '06-Mar-1968', 'Estele', 'Lucock', '7538 Mayfield Avenue');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (54, 91, '23-Nov-1996', 'Dom', 'Wakefield', '57860 Reinke Hill');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (1, 92, '13-Mar-1960', 'Brendis', 'Dell Casa', '870 Jackson Circle');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (34, 93, '21-Mar-1998', 'Ceil', 'Eccleston', '42 Almo Junction');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (27, 94, '29-Jun-1971', 'Judon', 'Di Iorio', '4 Morning Point');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (59, 95, '04-Jan-1985', 'Libbie', 'Spall', '63164 Carey Avenue');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (34, 96, '26-Nov-1995', 'Catherine', 'Castelletto', '0130 Pond Avenue');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (1, 97, '09-Jul-1968', 'Alysa', 'Wansbury', '3 Mosinee Point');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (44, 98, '27-Aug-1991', 'Gerry', 'Francecione', '19708 Cody Road');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (38, 99, '22-Jun-1973', 'Alejandro', 'Simak', '08 Mesta Plaza');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (53, 100, '27-Jun-1993', 'Ado', 'Flintuff', '653 Westerfield Alley');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (38, 101, '03-May-1961', 'Orelee', 'Arnaudot', '50481 Armistice Trail');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (26, 102, '11-May-1972', 'Wilfrid', 'Baser', '976 Dunning Terrace');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (32, 103, '11-Nov-1992', 'Rowen', 'Malone', '0 Golden Leaf Plaza');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (51, 104, '31-Jul-1973', 'Ryann', 'Crips', '42134 Westridge Junction');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (29, 105, '17-May-1975', 'Jenni', 'Whitely', '6 Sommers Place');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (42, 106, '08-Mar-1980', 'Linnie', 'Janowski', '994 Boyd Junction');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (22, 107, '15-Jan-1980', 'Burtie', 'McMoyer', '5988 Petterle Pass');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (47, 108, '22-Feb-1995', 'Orelee', 'Farland', '500 Johnson Terrace');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (38, 109, '23-Oct-1960', 'Codie', 'Goldine', '988 Monument Alley');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (41, 110, '25-Jun-1976', 'Arvin', 'Giamuzzo', '18 Pine View Hill');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (63, 111, '10-Jul-1977', 'Nannette', 'McFarland', '99 Graedel Center');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (12, 112, '08-Mar-1975', 'Rolland', 'Edmundson', '57733 Saint Paul Junction');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (56, 113, '10-Feb-1993', 'Dolores', 'Diggons', '95 Manitowish Junction');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (17, 114, '05-Feb-1977', 'Theadora', 'Reddings', '54 Mayer Road');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (27, 115, '12-Jan-1961', 'Dru', 'Fawdrey', '6 Texas Center');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (50, 116, '03-Oct-1967', 'Dilly', 'Tofpik', '186 Cardinal Park');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (62, 117, '01-Jan-1987', 'Annette', 'O'' Shea', '9 Erie Lane');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (20, 118, '11-Jun-1995', 'Karlie', 'Orniz', '671 Laurel Plaza');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (19, 119, '29-Aug-1961', 'Lebbie', 'Defond', '64440 Annamark Trail');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (59, 120, '29-Jan-1970', 'Lani', 'Stratton', '3304 7th Point');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (14, 121, '27-Dec-1981', 'Elisa', 'Frears', '39 Red Cloud Road');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (11, 122, '20-Sep-1994', 'Wernher', 'Asprey', '45133 Armistice Hill');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (35, 123, '15-Oct-1995', 'Stanton', 'MacGillespie', '271 Welch Center');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (34, 124, '20-Jun-1985', 'Jarad', 'Snell', '4 Portage Trail');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (63, 125, '20-Sep-1985', 'Wynn', 'Woodyatt', '687 Oak Street');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (19, 126, '12-Aug-1984', 'Price', 'Burren', '102 Johnson Parkway');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (47, 127, '23-May-1971', 'Michelle', 'Phippard', '3797 Barnett Point');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (60, 128, '30-Aug-1964', 'Ferne', 'Molfino', '788 Buhler Alley');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (4, 129, '15-Jun-1998', 'Kincaid', 'Preon', '7794 Emmet Place');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (24, 130, '18-Mar-1981', 'Hazlett', 'Devorill', '77 Bunting Crossing');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (54, 131, '05-Oct-1964', 'Noreen', 'Gabbott', '56 Chinook Pass');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (31, 132, '07-Aug-1962', 'Betsy', 'Bloore', '8 Knutson Pass');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (13, 133, '12-Apr-1962', 'Lucia', 'Lurriman', '5 Cottonwood Alley');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (8, 134, '16-Oct-1978', 'Maryellen', 'Sandbatch', '5140 Packers Road');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (44, 135, '02-Jan-1963', 'Claribel', 'Webland', '89022 Weeping Birch Alley');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (67, 136, '25-Apr-1993', 'Paco', 'McBride', '00813 Forest Place');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (33, 137, '13-May-1974', 'Towny', 'Jolley', '5 South Drive');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (3, 138, '24-Jan-1960', 'Osgood', 'Tockell', '5 Prentice Point');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (20, 139, '06-May-1961', 'Kyle', 'Pettifer', '80 Schmedeman Way');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (44, 140, '02-May-1970', 'Tore', 'Arrighetti', '0562 Clove Crossing');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (27, 141, '11-Sep-1961', 'Darsey', 'Begley', '198 Jenna Alley');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (61, 142, '19-Mar-1980', 'Meryl', 'Pocknell', '07057 Orin Court');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (46, 143, '21-Sep-1992', 'Cazzie', 'Shutle', '89747 Buhler Parkway');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (61, 144, '06-Mar-1968', 'Findley', 'Harget', '66 Moland Alley');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (50, 145, '11-Dec-1971', 'Cam', 'Buckles', '9 Dayton Plaza');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (29, 146, '01-Dec-1969', 'Linda', 'West-Frimley', '75573 Anderson Parkway');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (41, 147, '07-Nov-1960', 'Annmarie', 'Melrose', '716 Acker Plaza');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (29, 148, '13-Nov-1990', 'Shelbi', 'Caberas', '775 Longview Court');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (24, 149, '28-May-1970', 'Rozanna', 'Hynam', '755 Emmet Drive');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (41, 150, '28-Oct-1992', 'Audra', 'Rosini', '1388 Ridge Oak Park');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (34, 151, '25-Jul-1991', 'Llewellyn', 'Rulton', '9 Esker Lane');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (21, 152, '05-May-1999', 'Dallas', 'Leeson', '485 Mayfield Alley');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (30, 153, '14-Dec-1978', 'Luca', 'Eitter', '7375 Sage Parkway');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (56, 154, '30-Jun-1979', 'Bordie', 'Bennit', '62656 Artisan Court');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (61, 155, '11-Sep-1985', 'Curcio', 'Sommer', '5789 Maywood Junction');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (59, 156, '28-Oct-1998', 'Godwin', 'Linwood', '34826 Starling Parkway');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (52, 157, '08-Jan-1988', 'Elnar', 'Rumgay', '54609 Tony Alley');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (60, 158, '09-Feb-1978', 'Valma', 'Quennell', '74417 Swallow Pass');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (11, 159, '24-Jul-1974', 'Lamar', 'Habbin', '5468 Buhler Road');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (18, 160, '03-Apr-1971', 'Say', 'Torresi', '5733 Fulton Court');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (36, 161, '07-Apr-1973', 'Aarika', 'Ricci', '17 New Castle Circle');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (55, 162, '09-Mar-1989', 'Beverley', 'Kerton', '36 Nevada Street');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (55, 163, '22-Mar-1983', 'Brnaba', 'Garner', '5 Di Loreto Pass');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (50, 164, '15-Dec-1974', 'Marjory', 'Pearle', '79 Crowley Alley');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (11, 165, '13-Apr-1971', 'Ara', 'Merryfield', '8045 Larry Trail');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (31, 166, '19-Aug-1977', 'Selle', 'Sherar', '9055 Bayside Court');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (35, 167, '22-Aug-1977', 'Margy', 'Petrakov', '383 Becker Way');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (23, 168, '29-Oct-1981', 'Benito', 'Challen', '5587 Blaine Center');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (39, 169, '08-May-1964', 'Millard', 'Madner', '9794 Moulton Parkway');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (51, 170, '23-Jan-1960', 'Donaugh', 'Beckhouse', '209 Banding Place');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (45, 171, '19-Nov-1970', 'Jordan', 'Perford', '96223 Warbler Center');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (42, 172, '08-Sep-1979', 'Pincas', 'Mailes', '77 Mallard Way');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (51, 173, '24-Feb-1977', 'Hoebart', 'Bog', '77 Jackson Center');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (33, 174, '08-Dec-1979', 'Lishe', 'Treby', '71 Shasta Alley');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (19, 175, '05-May-1964', 'Delila', 'Longfellow', '787 Messerschmidt Center');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (58, 176, '15-Apr-1973', 'Dynah', 'Faloon', '72 Ridgeway Court');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (33, 177, '10-Mar-1991', 'Irena', 'Zollner', '47 Oak Avenue');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (63, 178, '19-Mar-1972', 'Roseann', 'Pickvance', '71404 Union Pass');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (47, 179, '10-Mar-1965', 'Delia', 'Phettiplace', '98 Ohio Crossing');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (17, 180, '01-Jan-1982', 'Gordon', 'Keuntje', '97692 Chive Parkway');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (50, 181, '09-Jul-1986', 'Shanan', 'Hackforth', '96 Sutherland Alley');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (29, 182, '05-Feb-1988', 'Sandie', 'Ridings', '2495 Comanche Pass');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (52, 183, '29-Sep-1963', 'Dwayne', 'Kegan', '4 Golden Leaf Plaza');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (46, 184, '13-Aug-1973', 'Corabel', 'Tilt', '72553 Bluejay Place');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (66, 185, '22-Feb-1965', 'Jenine', 'Thomsen', '0 Swallow Crossing');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (5, 186, '27-Apr-1995', 'Vitoria', 'Donson', '46140 Blackbird Point');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (11, 187, '07-Jul-1987', 'Kynthia', 'Kenchington', '277 Nancy Center');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (40, 188, '07-Dec-1993', 'Dunc', 'Silmon', '355 Fallview Court');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (36, 189, '02-Oct-1997', 'Griffy', 'Bendon', '0540 Delaware Point');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (24, 190, '15-Nov-1966', 'Culley', 'Babbe', '656 Ilene Center');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (34, 191, '05-Aug-1998', 'Gwenora', 'Wheadon', '794 Carpenter Lane');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (24, 192, '17-May-1961', 'Lenee', 'Stolworthy', '134 Oriole Place');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (14, 193, '25-Mar-1996', 'Shaughn', 'Puttergill', '39923 Holy Cross Road');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (14, 194, '04-Feb-1985', 'Mufinella', 'Circuitt', '17454 Milwaukee Place');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (18, 195, '03-Feb-1987', 'Devi', 'Dingwall', '127 Schmedeman Center');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (12, 196, '16-Oct-1973', 'Den', 'Ygou', '985 Bluestem Terrace');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (43, 197, '18-Jul-1970', 'Brandais', 'Fallows', '82832 Arkansas Drive');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (52, 198, '21-Feb-1961', 'Leah', 'Garnsworthy', '39 Sunbrook Drive');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (2, 199, '22-Feb-1973', 'Antonie', 'Marklund', '957 Algoma Terrace');
insert into MLJ_CUSTOMER (MLJ_CITY_cityId, customerId, dateOfBirth, customerName, customerLastName, adress) values (32, 200, '18-Mar-1992', 'Bryn', 'Afield', '8 Eliot Place');